name = "squad-hr"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "squad-hr-db"
database_id = "136ffc78-22f5-4556-8f0a-c3593a7a6d73"
migrations_dir = "migrations"
